language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

addons:
  apt:
    packages:
      # We need build-essential because this project needs gcc to autogenerate and compile C programs
      - build-essential
      - libfreetype6:i386
      # The gcc-multilib is because in this project we automatically generate C programs that include libc
      # headers and these are included only if installing gcc-multilib
      - gcc-multilib

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-alpha
  - Pharo-5.0
