language: c
os:
  - linux
addons:
  apt:
    packages:
      - lib32asound2
      - lib32z1
      - lib32bz2-1.0
      - libssl1.0.0:i386
      - build-essential
      - gcc-multilib
      - libfreetype6:i386
script: 
  - scripts/run-tests.sh  